version: "3.8"
services:
  api:
    build: .
    restart: always
    env_file:
      - .env
    environment:
      ROOT_PATH: /
    ports:
      - "8001:8001"
    depends_on:
      - db
  
  worker:
    build: .
    command: python -m app.worker.worker
    depends_on:
      - api
    restart: always

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: qwerty
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: archive_db
      
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: