name: Deploy to Server

on:
    push:
      branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Copy files to server via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/schelper_server
            echo ">>> Pulling latest code"
            git fetch --all
            git reset --hard origin/main

            echo ">>> Rebuilding Docker image"
            docker compose -f docker-compose.yml build --no-cache

            echo ">>> Restarting containers (API + Webapp)"
            docker compose -f docker-compose.yml down
            docker compose -f docker-compose.yml up -d

            echo ">>> Deployment finished!"

